### ISSUE TITLE
SHOW_PERSON_OUTLINE renders external Person as internal

### ISSUE THREAD

**Issue by chriskn** [plantuml-stdlib/C4-PlantUML#265] opened 2022-11-19 14:30 UTC
The following diagram:
```
@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person_Ext(8, "Person A")

SHOW_LEGEND(true)

@enduml
```

is rendered as expected:
![grafik](https://user-images.githubusercontent.com/1077869/202855490-daf8eff9-d818-40b5-8c31-84a40742d50e.png)

With the SHOW_PERSON_OUTLINE option:
```
@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

SHOW_PERSON_OUTLINE()

Person_Ext(8, "Person A")

SHOW_LEGEND(true)

@enduml
```

External Person is rendered as internal, while the legend still contains `external_person`:
![grafik](https://user-images.githubusercontent.com/1077869/202855621-b580a1c8-b9b5-477b-99a0-ea8795f25940.png)

The issue exists for Context, Container and Component diagrams. The issue was likely introduced with release 2.4.0., at least I did not notice it before.

**Comment by kirchsth** [comment] 2022-11-19 21:30
@chriskn:

 **which PlantUML version are you using?**
I tried it in with the current  PlantUML web server and cannot reproduce the problem.
(I extended it after my first test with the C4Version() and %version() that the C4 and PlantUML are displayed too)

```plantuml
@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

SHOW_PERSON_OUTLINE()

Person_Ext(8, "Person A")
Person_Ext(version, %version())
Person_Ext(C4Version, C4Version())

SHOW_LEGEND(true)
@enduml
```

![](https://www.plantuml.com/plantuml/png/LOvHIuKm68RlzolMWM32EUx6Y-ZAi561gMJMvPWwSZ0tsRwLFp-7nS6xP--Ub_VBFGW7OTReHfb1Xr46f_44iFXxIftuIRyKJA4FNhh16f06qi7ETD72nDh5mwXLJuliqiIeUotfB3n8jqMyY8qLqYKEeFQv_kGDUslhYjVTU_bICP8Wr4ZdhU5i1N9tngVzYHzEnw_l3PKrPtpxHoGv2aNsyQz4l3hxRicUMFL8m0MPe5oQSJlf5m00)

BR Helmut

**Comment by chriskn** [comment] 2022-11-20 10:31
Hi @kirchsth 

```
@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

SHOW_PERSON_OUTLINE()

Person_Ext(version, %version())
Person_Ext(C4Version, C4Version())

SHOW_LEGEND()

@enduml
```

![grafik](https://user-images.githubusercontent.com/1077869/202897103-6ad10333-dee8-4d4a-a5cd-540764220b46.png)

**Comment by kirchsth** [comment] 2022-11-20 10:38
Can you try it with the PlantUML deployed C4-stdlib?

```
@startuml
!includeurl <C4/C4_Container.puml>

SHOW_PERSON_OUTLINE()

Person_Ext(version, %version())
Person_Ext(C4Version, C4Version())

SHOW_LEGEND()
@enduml
```

**Comment by chriskn** [comment] 2022-11-20 10:42
That one works as expected: 
![grafik](https://user-images.githubusercontent.com/1077869/202897657-401059ca-5af5-4ee7-a992-fbf1b0c126f9.png)

I wasn't aware of this include url schema. Are these includes something like the "stable" versions?

**Comment by kirchsth** [comment] 2022-11-20 13:53
>> !includeurl <C4/C4_Container.puml>; I wasn't aware of this include url schema. ...
As soon we have a new release we export it to the PlantUML-stdlibs too that it can be used without any additional includes ...

**related to the different outputs**
I found problems with other diagrams too, e.g. in following sample the color of the person label should be yellow(==background) and not green (the Person_Ext has the correct gold color)

```
@startuml
!include <C4/C4_Context.puml>

UpdateElementStyle("person","yellow","green","blue")
UpdateElementStyle("external_person","gold", "red", "darkred")

' SHOW_PERSON_OUTLINE()
SHOW_PERSON_PORTRAIT()
Person(version3, "uiuzdsiss")
Person_Ext(versi4, "uiuzdidfsaf")

SHOW_LEGEND(false)
@enduml
```

correct via PLantUML web server 
![](https://www.plantuml.com/plantuml/png/ROz1IyD048Nl-olYNaoWwC4SHIfnqKB9XYJ5uxAwOrcSxeRDhBR-UiSMfGTFytWVxuDPpcGJvHsA2nzUCJieRflwkgbD4mF1dgucXdT2R2Pd2HJ23W8DT40evGHfZa4kv04GuoU7RGBuALumWwp-7R4JKh1e_jRRY4uk2fdWU9nDxnnvBYwBuKa_cqxrWswDtephLQlAIfotdUx7_durSjqTZUK77n_33Rkopr_Eorzar9vEk3w79zzQFQhseNopE4CbbX0SV_uD)

wrong with IntellijPlugin
 
![diag-dae5b608de1db526e54717a9e8752618](https://user-images.githubusercontent.com/21959385/202905190-ae77bd3e-35f8-4357-823b-31c1331f85ce.png)

I compared the extracted metadata of both images and

- both uses the exact same plantuml preprocessore source 

- the only found difference was the different different source distributions :

  - (working) PlantUML Web Server

```
PlantUML version 1.2022.13beta8(Unknown compile time)
(GPL source distribution)
Java Runtime: Java(TM) SE Runtime Environment
JVM: Java HotSpot(TM) 64-Bit Server VM
Default Encoding: UTF-8
Language: en
Country: US
``` 

  - (not working) PlantUML integration for IntelliJ in version 5.19

```
PlantUML version 1.2022.5(Sat Apr 30 12:55:52 CEST 2022)
(APACHE source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Default Encoding: Cp1252
Language: en
Country: US
```

**Comment by kirchsth** [comment] 2022-11-20 14:43
I found the problem: "PlantUML integration for IntelliJ" uses an too old plantuml.jar version. If they update to the last plantuml.jar version it should work again.

**Details:**

If an older plantuml version is used (I checked it with plantuml.1.2022.2) 
```plantuml
skinparam person<<person>> {
    FontColor green
}
```
overwrites the actor specific skinparam too
```plantuml
skinparam actor<<person>> {
    FontColor yellow
}
```
which should not be the case (and it is fixed in the meantime)

it can be tested with following

```plantuml
@startuml

skinparam actor {
    StereotypeFontSize 12
    shadowing false
    style awesome
}

skinparam actor<<person>> {
    StereotypeFontColor yellow
    FontColor yellow
    BackgroundColor yellow
}
skinparam person<<person>> {
    StereotypeFontColor green
    FontColor green
    BackgroundColor yellow
}

skinparam actor<<external_person>> {
    StereotypeFontColor gold
    FontColor gold
    BackgroundColor gold
}
skinparam person<<external_person>> {
    StereotypeFontColor red
    FontColor red
    BackgroundColor gold
}

actor "==uiuzwreerqwrrrqrrqdi" <<person>> as version3
actor "==uiuzdi" <<external_person>> as versi4

@enduml
```

If an old version is used the `yellow actor<<person>> font` is overwritten with the wrong `green person<<person>> font`.
In the newer versions the bug is fixed and the actor font remains yellow. (`<<external_person>>`  is not affected by the bug)

**Comment by kirchsth** [comment] 2022-11-20 16:21
@chriskn can you please test my added workaround #266?

**Comment by Potherca** [comment] 2022-11-21 10:34
It might be worth noting that the IntelliJ plugin for PlantUML has an option to use a local plantuml.jar (instead of the bundled one).

**Closed** 2022-11-26 21:51 UTC
