### ISSUE TITLE
IntelliJ Live templates point to old repository

### ISSUE THREAD

**Issue by LosD** [plantuml-stdlib/C4-PlantUML#286] opened 2023-01-24 12:11 UTC
Hi there, the live templates (those that generate the skeleton for at diagram) doesn't point to the plantuml-stdlib repo, but to @RicardoNiepel's old repo.

#### Actual link
`!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml`

#### Expected link
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

If you decide to change it, you might as well also change to `!include` instead of `!includeurl`, since the library itself doesn't seem to support any version of PlantUML that doesn't also support `!include` for URLs.

**Comment by Potherca** [comment] 2023-01-28 15:58
@LosD Thank you for reporting this!

I'm away on vacation for the coming week, but I'll have a look when I get back. 👍

**Comment by kirchsth** [comment] 2023-06-11 14:13
Hi @Potherca, do you have time for the update?
If yes we could at it to release 2.7.0
Thank you and best regards
Helmut
PS.: I have no MACOS that I can create this part of the zip too

**Comment by Potherca** [comment] 2023-06-20 14:12
I'm afraid that work demands and ill health have been playing up again. Little to no time available for contributions at the moment. 😞

**Comment by kirchsth** [comment] 2024-03-17 16:32
cleanup stalled issue.
If the problem is still relevant please reopen it.

**Comment by kirchsth** [comment] 2024-03-27 21:21
fixed with #344

**Closed by kirchsth** 2024-03-27 21:21 UTC
Labels: help wanted

**Comment by vipinthomasvertexinc** [comment] 2024-03-28 03:08
@kirchsth , I didn't change !includeurl to !include. It still works for me though.
