### ISSUE TITLE
Custom images

### ISSUE THREAD

**Issue by mohanr** [plantuml-stdlib/C4-PlantUML#24] opened 2019-07-03 09:49 UTC
```
> package "Other Groups" {
> FTP - [Second Component]
> note left
>  You can use images
> <img:D:\TensorBoard\DB2-Setup.jpg{scale=0.3}>
> end note
> [First Component] --> FTP
> }
```
This code works if I don't use the C4 plugin.
This also works with the C4 plugin if I don't use the `img` tag.

**Comment by adrianvlupu** [comment] 2019-10-20 18:02
This seems to be more of an issue with plantuml rather than the C4 plugin.

![image](https://user-images.githubusercontent.com/4486850/67163661-3a3ac300-f37a-11e9-973c-da173e5a273d.png)

It seems to be caused by `skinparam WrapWidth` if you add that to any diagram containing an image it breaks.

A solution would be adding `skinparam WrapWidth 0` in the diagram you are using the images, but then you have to add `\n` to break lines in your text.

![image](https://user-images.githubusercontent.com/4486850/67163850-c51cbd00-f37c-11e9-9db7-cd73880d6eda.png)

**Comment by Potherca** [comment] 2020-11-22 20:11
Closing as this issue lies in the upstream project PlantUML and can not be fixed in this repo.

**Closed by Potherca** 2020-11-22 20:11 UTC
Labels: Can't Fix
